### ISSUE TITLE
点赞反馈按钮z-index层级BUG

### ISSUE THREAD

**Issue by Exrick** [alibaba/ChatUI#17]
点赞反馈按钮悬浮于快捷回复之上了 官网可复现

![WX20210118-224035@2x.png](https://i.loli.net/2021/01/18/xfoWFOSY5LDAB4u.png)

图片链接 https://i.loli.net/2021/01/18/xfoWFOSY5LDAB4u.png

将`.RateActions`的z-index改为10以下可解决
```css
.RateActions {
    ...
    z-index: 10;
    ...
}
```
