### ISSUE TITLE
How to config chatUI like this in react?

### ISSUE THREAD

**Issue by dimasna** [alibaba/ChatUI#24]
How to config chatUI like this ? 
![image](https://user-images.githubusercontent.com/30913369/109542289-739b4b00-7af7-11eb-96d8-51bd31d88093.png)

**Comment by akai** [comment]
```css
.Composer-actions[data-action-icon="plus"] {
    order: 1;
    margin: 0 8px 0 0;
}

.Composer-inputWrap {
    order: 2;
}

.Composer-actions[data-action-icon="mic"] {
    position: absolute;
    right: 0;
    z-index: 1;
}
```

and apply abs to speech input
